
export const ADD_INPUT_VALUE = "ADD_INPUT_VALUE";

export const REMOVE_INPUT_VALUE = "REMOVE_INPUT_VALUE";

export const EDIT_INPUT_VALUE = "EDIT_INPUT_VALUE";

export const GET_ISD_DATA="GET_ISD_DATA"
